version: '3.8'
services:
  DEV_SERVICE_NAME:
    container_name: ${BTA_BC_CONNECTOR_NAME}
    image: ${BTA_BC_CONNECTOR_IMAGE}-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - ${APP_PORT}:3000
    networks:
      - bta-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

  PROD_SERVICE_NAME:
    container_name: ${BTA_BC_CONNECTOR_NAME}_prod
    image: ${BTA_BC_CONNECTOR_IMAGE}-prod:1.0.0
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    command: npm run start:prod
    ports:
      - ${APP_PORT}:3000
    networks:
      - bta-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file: .env
    restart: unless-stopped

networks:
  bta-network:
